name: Deploy to Heroku (Docker)

on:
  push:
    branches: [main]

concurrency:
  group: heroku-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install the Heroku CLI in this runner
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Verify Heroku CLI
        run: |
          command -v heroku
          heroku --version
          heroku auth:whoami || true   # just to show it's reading HEROKU_API_KEY

      - name: Login to Heroku Container Registry
        run: heroku container:login

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release to Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
