name: Deploy to Heroku (Docker)

on:
  push:
    branches: [main]

concurrency:
  group: heroku-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install & configure Heroku CLI (uses your API key)
      - name: Set up Heroku CLI
        uses: heroku/actions/setup-heroku@v2
        with:
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}

      # (Optional) login to Docker Hub if you pull private bases
      # - name: Docker Hub login
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Heroku Container Registry
        run: heroku container:login

      - name: Build Docker image
        run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker image
        run: docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release to Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
